---
- name: Establish some role-related facts
  set_fact:
    mongodb_major_version: "{{ mongodb_version[0:3] }}"
  tags: mongodb

- name: Add YUM repository
  template:
    src: mongodb.repo.j2
    dest: /etc/yum.repos.d/mongodb.repo
    mode: 0644
  with_items: "{{ mongodb_major_version }}"
  loop_control:
    loop_var: version_item
  when: mongodb_package == 'mongodb-org'
  tags: mongodb

- name: Install MongoDB package
  yum:
    name: "{{ mongodb_package }}{% if (mongodb_version | length > 3) %}={{ mongodb_version }}{% endif %}"
    state: "{{ mongodb_package_state }}"
  tags: mongodb

- name: Install numactl package
  yum:
    name: numactl
    state: present
  tags: mongodb

- name: Install PyMongo package
  yum:
    name: python-pymongo
    state: present
  when: not mongodb_pymongo_from_pip
  tags: mongodb

- name: Install PIP
  yum:
    name:
      - python-devel
      - python-pip
    state: present
  when: mongodb_pymongo_from_pip
  tags: mongodb

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    state: "{{ mongodb_pymongo_pip_version is defined | ternary('present', 'latest') }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
  when: mongodb_pymongo_from_pip
  tags: mongodb
